### ISSUE TITLE
Compiling the library

### ISSUE THREAD

**Issue by yvesdm3000** [stoth68000/libklvanc#51]
Hi,

I tried compiling the library but I can't find any declaration of "struct buffer_s"  ? Maybe a file not checked in?

Yves

**Comment by stoth68000** [comment]
Thanks for the report.

It's compiling fine for me.
git clone https://github.com/stoth68000/libklvanc
./autogen.sh --build
./configure --enable-shared=no
make -j8

**Comment by yvesdm3000** [comment]
Yes, moving it into our build system with CMake... I removed the files that use buffer_s and it's fine now. Tnx for the library !
