### ISSUE TITLE
HDMI REC trigger

### ISSUE THREAD

**Issue by FilipCZE** [stoth68000/libklvanc#66]
is:issue is:open Hi! Im very excited about this project. Im still reading how to catch VANC date from my SONY camera which support sending REC trigger over the HDMI. This project seems to be solution for me. I would like to use HDMI to USB or HDMI to CSI (C779) adapter to be able to recieve video stream and hope also the VANC where should be hidden that REC flag... Would you be kind and tell me more about this - if you know more? Thanks!

**Comment by dheitmueller** [comment]
So REC triggers are typically sent as user bits within the timecode (which in SDI is over HANC and in HDMI is sent a dedicated HDMI extension for timecodes).  It's not available in VANC and hence not applicable to libklvanc.

If you're using a Blackmagic decklink device to try to see the REC trigger on capture over HDMI, take a look at the BMDTimecodeFlags field provided back to applications via the IDeckLinkTimecode::GetFlags() method.

Closing this ticket as it's not an issue for libklvanc.

**Comment by stoth68000** [comment]
Closing.
