### ISSUE TITLE
Illegal cc_count received

### ISSUE THREAD

**Issue by tvadi** [stoth68000/libklvanc#68]
Hi, first I want to thank all who made libklvanc, it works amazing and I am so grateful! 

So running Ubuntu 21.10, ffmpeg compiled with libklvanc and Decklink, playing great out the SDI, I can see my captions on the broadcast monitor while playing files, all is well for file based playback with 608/708 embedded mpegs TS files.  

My next step is to get the SRT stream from OBS out the Decklink and hopefully maintain the captions it is generating with it's "Cloud Closed Captions" plug-in. [https://github.com/ratwithacompiler/OBS-captions-plugin](url) it uses Google Cloud Speech Recognition to listen to the audio from the live video happening on OBS and adds captions automatically. OBS can output via SRT and it will pass these captions in the SRT stream. 

To view the OBS plug in at work, simply install it, set source to caption, activate and stream by setting the stream server to Custom and service to:
`srt://127.0.0.1:10000?mode=listener`
Then, just open in MPV player:
`mpv srt://127.0.0.1:10000`

Then click on the text/ keyboard icon in MPV and you will see the captions.  Now when I open the stream in ffmpeg with:

`ffmpeg -i srt://127.0.0.1:10000 -pix_fmt yuv420p -f decklink -vcodec v210 "DeckLink SDI 4K"`
I get a ton of 
`Illegal cc_count received` errors
Video plays out the Decklink, but no captions show.
Wondering if I need to add something more in my ffmpeg line or more likely the OBS is not putting out CEA compliant captions and thus the Illegal cc_count received errors?
[https://github.com/obsproject/obs-studio/issues/4006](url)

Guessing the above ticket is the issue but looking to be sure and any guidance on what they need to do to fix this as I will follow up with the OBS folks too.  Thanks in advance!

**Comment by dheitmueller** [comment]
Hi Matt,

So it is the responsibility of the upstream source to properly send the correct number of tuples, based on the framerate of the underlying video.  If you're seeing "illegal cc_count" errors then it's likely that the original upstream source went through some sort of framerate conversion but didn't repack the stream.

For example, with 720p59 video the cc_count must be 10, and with 1080i59 video the cc_count must be 20.  If the video had an original framerate of 720p59 and was framerate-converted to 1080i59, the each frame of the resulting video should contain 20 cc tuples.

Within ffmpeg I accomplish this with the introduction of a FIFO which repacks the series of tuples with each frame based on the target framerate, and it's hooked in to each filter which changes the framerate.

https://github.com/LTNGlobal-opensource/FFmpeg-ltn/blob/lted1/libavutil/cc_fifo.c

I also have a filter which does the repacking if the cc_count is simply wrong and the data is intact.  However it's worth noting that this doesn't help if some prior filter discarded half the caption data or duplicated it (as would be the common outcome from framerate changes).  If you see double characters or every other character is missing, this filter won't help.

https://github.com/LTNGlobal-opensource/FFmpeg-ltn/blob/lted1/libavfilter/vf_ccrepack.c

**Comment by tvadi** [comment]
Thank you for the thorough info.  In testing with the OBS SRT stream, when I turn off the captions plug in, I no longer get the "illegal cc_count" errors and my SDI monitor is showing good 720p 59.94 video out of the SDI either way so I think the issue is the captions count like you say.  

Just not sure where the frame rate conversion/ error introduction would be happening, the output from OBS is set to 1280x720 59.94, although it does not specify progressive or interlaced.  But is I am not getting the error with the captions plug in off, it would seem that is where the problem is.  Could it be that the captions are at one frame rate and the video another or something like this?

I'm not a programmer but can try and dig into this and see if I can work with the OBS guys to figure out a fix.  To clarify, if I added FIFO and vf_ccrepack to my ffmpeg build, would I be able to force the captions/ frame rate to be correct?  Or this is something OBS would need to implement?

**Comment by dheitmueller** [comment]
I would probably first see if the output of OBS without ffmpeg has captions that are rendering properly.  If you are expecting to see "Hello World" but the rendered output is "HHeelloo  WWoorrlldd" or "HloWrd" then you've got a framerate conversion problem within OBS where the data is being duplicated or every other frame dropped, in which case it *must* be fixed in OBS.  

If they are simply always setting the cc_count to a fixed value regardless of the framerate (i.e. they always output a cc_count of 20 even the video is 59.94 frames per second), then putting the vf_repack filter into the ffmpeg pipeline will correct that issue.

It's worth noting that I don't think the plugin itself is the issue, as the plugin just does speech to text and the output is composed text strings (i.e. not CEA-608/708 captions).  The OBS core is responsible for taking those strings and creating the 708 caption data that is inserted into the MPEG-TS output.

In any case, there's no indication this is a libklvanc problem, so I'm going to recommend this issue be closed and feel free to email me directly to discuss further.

**Comment by tvadi** [comment]
Sure, I have seen bad captions like that in other situations, I am not seeing that.  The only way to see the captions stream is with MPV player, and while they do not have the "HHeelloo WWoorrlldd" or "HloWrd" problem, they do seem to jump a bit, like it will give the text pretty fast and maybe the Google cloud speech recognition is a bit sporadic, looks a lot like it does if you are doing talk to text on your phone, a word may flash on for a second, then off while the speech recognition is making sure it is right, then the word is back on and stays..  

So I don't think it is a frame rate issue, I think you are right and it is OBS not conforming the text to proper 708 or 608.  Have read on other strings that this may be a known issue..
Ratwithacompiler just confirmed: "My plugin basically just regularly calls obs_output_output_caption_text2("latest caption lines") and all the actual creating and embedding CEA captions into the video stream is fully done by OBS itself so any fixes like that would have to go into OBS itself."  Thanks for your help, feel free to close

**Comment by stoth68000** [comment]
Closing.
