### ISSUE TITLE
Should core-packet-smpte_2108_1.c be linked in?

### ISSUE THREAD

**Issue by TriveniSean** [stoth68000/libklvanc#78]
I was just messing around with an MSYS2 build and I noticed that the meson.build didn't reference core-packet-smpte_2108_1.c

`ld.exe: src/libklvanc.dll.p/core-packets.c.obj:core-packets.c:(.rdata+0x3a8): undefined reference to 'parse_SMPTE_2108_1'
ld.exe: src/libklvanc.dll.p/core-packets.c.obj:core-packets.c:(.rdata+0x3b0): undefined reference to 'klvanc_dump_SMPTE_2108_1'`

The linker was grumpy until I added it.

**Comment by dheitmueller** [comment]
@TriveniSean Thanks for the feedback.  Yes, the file should be added to the meson file.  The Meson spec was contributed by a third-party and isn't part of our standard build process, so stuff like this sometimes gets overlooked.

**Comment by dheitmueller** [comment]
The fix for this is in https://github.com/stoth68000/libklvanc/pull/76 and should be merged.  After merge this bug can be closed.
